[user]
output_dir = "dist/"
links_path = "index.html"

[db]
url = "sqlite:///links.db"

[search]
enabled = true

[ai]
enabled = true
url = "http://localhost:11434/v1"
api_key = "ollama"
model = "llama3.2"
